name = Provisioner-Recipe
version = 1.000
author = George S. Baugh <george@troglodyne.net>
license = MIT
copyright_holder = Troglodyne LLC
copyright_year = 2026

; Simpler than doing include_dotfiles
[Run::AfterBuild]
run = cp .perltidyrc .build/latest/.perltidyrc
run = cp .perlcriticrc .build/latest/.perlcriticrc
run = cp .preferred_modules.ini .build/latest/.preferred_modules.ini

[GatherDir]
exclude_filename = AGENTS.md
exclude_filename = VISION.md
exclude_filename = STYLE.md
exclude_filename = ipmap.cfg
exclude_filename = recipes.yaml
exclude_filename = secrets.kdbx
exclude_match    = cover_db/.+
exclude_match    = docs/.+
exclude_match    = recipes.d/.+
[MetaYAML]
[MetaJSON]
[License]
[Readme]
[InstallGuide]
[ExtraTests]
[ExecDir]
[ShareDir]
[MakeMaker]
[Manifest]
[PruneFiles]
[PruneCruft]
[ManifestSkip]
[Git::Check]
    allow_dirty = dist.ini
    allow_dirty = Changes
[Git::Commit / Release_Commit]
    allow_dirty = dist.ini
    allow_dirty = Changes
    add_files_in = /
    commit_msg = %v%n%n%c
[Git::Tag]
    tag_format = %v
    tag_message = %v
[Git::Push]
[TestRelease]
[ConfirmRelease]
[UploadToCPAN]
[MetaMergeFile]
[PrereqsFile]
[MetaNoIndex]
    directory = t
    directory = templates
    directory = docs
[MetaProvides::Package]
    inherit_version = 0

[AutoPrereqs]
[PkgVersion]

[PodWeaver]
[Git::Contributors]

[@TestingMania]
critic_config = .perlcriticrc
changelog = CHANGES
disable = Test::Portability

[CheckMetaResources]
[CheckPrereqsIndexed]
[CheckChangesHasContent]

[GithubMeta]
issues = 1
user = teodesian

; `dzil authordeps` doesn't know about the Pod Weaver dependencies:
; authordep Pod::Weaver::Section::Contributors = 0
; authordep Pod::Weaver::Plugin::Encoding = 0
; authordep Pod::Weaver::Section::SeeAlso = 0
; authordep Pod::Weaver::Section::GenerateSection = 0
; authordep Pod::Elemental::Transformer::List = 0

; Nor are the perl-critic deps included...
; authordep Perl::Critic::Policy::Modules::RequirePerlVersion  = 0
; authordep Perl::Critic::Policy::Documentation::RequirePod  = 0
; authordep Perl::Critic::Policy::ValuesAndExpressions::PreventSQLInjection  = 0
; authordep Perl::Critic::Policy::CodeLayout::RequireASCII  = 0
; authordep Perl::Critic::Policy::RegularExpressions::RequireDefault  = 0
; authordep Perl::Critic::Policy::BuiltinFunctions::ProhibitDeleteOnArrays  = 0
; authordep Perl::Critic::Policy::Subroutines::ProhibitAmbiguousFunctionCalls  = 0
; authordep Perl::Critic::Policy::ValuesAndExpressions::ProhibitSingleArgArraySlice  = 0
; authordep Perl::Critic::Policy::Bangs::ProhibitUselessRegexModifiers  = 0
; authordep Perl::Critic::Policy::Bangs::ProhibitCommentedOutCode  = 0
; authordep Perl::Critic::Policy::Tics::ProhibitUseBase  = 0
; authordep Perl::Critic::Policy::Plicease::ProhibitLeadingZeros  = 0
; authordep Perl::Critic::Policy::RegularExpressions::ProhibitEmptyAlternatives  = 0
; authordep Perl::Critic::Policy::ValuesAndExpressions::UnexpandedSpecialLiteral  = 0
; authordep Perl::Critic::Policy::CodeLayout::ProhibitIfIfSameLine  = 0
; authordep Perl::Critic::Policy::ValuesAndExpressions::ConstantBeforeLt  = 0
; authordep Perl::Critic::Policy::ValuesAndExpressions::ProhibitDuplicateHashKeys  = 0
; authordep Perl::Critic::Policy::ValuesAndExpressions::ProhibitFiletest_f  = 0
; authordep Perl::Critic::Policy::ValuesAndExpressions::ProhibitFiletest_rwxRWX  = 0
; authordep Perl::Critic::Policy::CognitiveComplexity::ProhibitExcessCognitiveComplexity  = 0
; authordep Perl::Critic::Policy::Variables::ProhibitUselessInitialization  = 0
; authordep Perl::Critic::Policy::PreferredModules  = 0
; authordep Perl::Critic::Policy::logicLAB::RequireSheBang  = 0
; authordep Perl::Critic::Policy::logicLAB::ProhibitShellDispatch  = 0
; authordep Perl::Critic::Policy::Performance::ProhibitRegexForSimpleSubstring  = 0
; authordep Perl::Critic::Policy::CompileTime  = 0
