name = Provisioner-Recipe
version = 1.000
author = George S. Baugh <george@troglodyne.net>
license = MIT
copyright_holder = Troglodyne LLC
copyright_year = 2026

[Git::GatherDir]
[MetaYAML]
[MetaJSON]
[License]
[Pod2Readme]
[PodSyntaxTests]
[Test::ReportPrereqs]
[Test::Compile]
    xt_mode = 1
[Manifest]
[PruneCruft]
[PruneFiles]
[ManifestSkip]
[RunExtraTests]
[Git::Check]
    allow_dirty = dist.ini
    allow_dirty = Changes
[Git::Commit / Release_Commit]
    allow_dirty = dist.ini
    allow_dirty = Changes
    add_files_in = /
    commit_msg = %v%n%n%c
[Git::Tag]
    tag_format = %v
    tag_message = %v
[Git::Push]
[TestRelease]
[ConfirmRelease]
[UploadToCPAN]
[MetaMergeFile]
[PrereqsFile]
[MetaNoIndex]
    directory = t
    directory = xt
    directory = inc
    directory = share
    directory = eg
    directory = examples
[MetaProvides::Package]
    inherit_version = 0
[ShareDir]
[ExecDir]

[AutoPrereqs]
[PkgVersion]

[PodWeaver]
[Git::Contributors]

[@TestingMania]
disable = PodSyntaxTests
critic_config = .perlcriticrc
changelog = CHANGES

[CheckMetaResources]
[CheckPrereqsIndexed]
[CheckChangesHasContent]

[GithubMeta]
issues = 1
user = teodesian

; `dzil authordeps` doesn't know about the Pod Weaver dependencies:
; authordep Pod::Weaver::Section::Contributors = 0
; authordep Pod::Weaver::Plugin::Encoding = 0
; authordep Pod::Weaver::Section::SeeAlso = 0
; authordep Pod::Weaver::Section::GenerateSection = 0
; authordep Pod::Elemental::Transformer::List = 0
