# For the self-signed certificate that the ssl target of templates/makefile.tt
# makes.  bin/new_config copies it into the configuration of every domain.
[req]
distinguished_name=dn
[ dn ]
[ ext ]
basicConstraints=CA:TRUE,pathlen:0
