package Provisioner::Recipe::emulatorjs;

#ABSTRACT: Self-host a single EmulatorJS game.

use 5.041;

use strict;
use warnings FATAL => 'all';
use re '/aa';

use parent qw{Provisioner::Recipe};

use Text::Xslate();

=head1 Provisioner::Recipe::emulatorjs

=head2 SYNOPSIS

    somedomain:
        emulatorjs:
            version: 4.2.3
            core: nes
            rom: supermariobros.nes
            game_title: Super Mario Bros.

=head2 DESCRIPTION

Serves L<EmulatorJS|https://github.com/EmulatorJS/EmulatorJS> -- a browser
emulator with no server-side component -- at the domain itself.

One domain is one game.  EmulatorJS supplies the engine and the cores; it does
not supply a library UI to pick among several, and inventing one is not this
recipe's job.  A cabinet with more than one game is more than one domain, the
same way a second gogs instance is a second domain rather than a second vhost
on the first.

=head3 Directory structure

Everything lives under C<install_dir/domain>, same as C<nginxdirindex>:

    engine/       the pinned EmulatorJS checkout -- loader, cores, wasm.  Public
                   code fetched straight off GitHub; nothing here is secret.
    roms/          the one ROM this domain serves.  Not generated by this
                   recipe -- an operator's own copyrighted file, dropped where
                   the C<data> recipe's rsync already puts a domain's content.
    index.html     the game page, rendered from C<game_title>, C<core> and C<rom>.

C<roms/> is deliberately not this recipe's C<datadirs>: C<data> runs first and
rsyncs the domain directory before this recipe's target does anything, so a
ROM an operator has placed at C<data_source/domain/roms/> on the hypervisor is
already there by the time C<engine/> is cloned.  Nothing here manufactures a
ROM, and nothing here should.

=head3 Why this needs its own vhost

C<nginxproxy> requires a C<proxy_uri> on every vhost that is not a redirect --
there is nothing here to proxy to, so this follows C<nginxdirindex> instead and
requires C<nginx> directly.

=head3 Why SSL is not optional

EmulatorJS's threaded cores need C<SharedArrayBuffer>, which a browser grants
only to a page that has cross-origin-isolated itself with
C<Cross-Origin-Opener-Policy> and C<Cross-Origin-Embedder-Policy> -- and a
browser will not consider a plain HTTP page a secure context to isolate in the
first place.  Port 80 redirects rather than serving, the way C<gogs> and
C<tcms> do.

=head3 args

C<version> pins the git tag C<engine/> is checked out at, the same way
C<gogs>'s C<version> does -- there is no default, because a recipe defaulting
to whatever a moving branch currently points at is a recipe that changes the
guest on a re-provision nobody asked for.

C<core> and C<rom> are EmulatorJS's own C<EJS_core> and the ROM filename under
C<roms/>; both are required, since a game page naming neither is a blank page.
Both are also filenames or filename-shaped identifiers, and both land inside a
single-quoted JS string in C<index.html> -- so the schema holds them to the
characters a filename should have anyway, which happens to be everything a JS
string literal never has to escape.

=head3 formatters

C<game_title> is free text, not a filename, and is escaped through
C<js_string> before it lands in the same JS literal -- see C<index.html.tt>.

=cut

sub required_recipes {
    return (
        nginx => sub { () },
    );
}

sub deps {
    my ($self) = @_;
    if ( $self->{target_packager} eq 'deb' ) {
        return qw{git};
    }
    die "Unsupported packager";
}

sub args {
    return (
        required   => [qw{version core rom}],
        properties => {
            # Also a git ref, and interpolated into a single-quoted argument to
            # git clone -- the same reason mariadb and imagemagick hold their
            # own version to a safe character set.
            version => { type => 'string', pattern => '^[A-Za-z0-9_.-]+$' },

            # Overridable for a fork or a mirror; not something most
            # configurations need to say.
            repo_url => { type => 'string', default => 'https://github.com/EmulatorJS/EmulatorJS.git' },

            core       => { type => 'string', pattern => '^[A-Za-z0-9_.-]+$' },
            rom        => { type => 'string', pattern => '^[A-Za-z0-9_.-]+$' },
            game_title => { type => 'string', default => '' },

            ipv6    => { type => 'boolean', default => 1 },
            backlog => { type => 'integer', default => 32768, minimum => 0 },
        },
    );
}

sub formatters {
    return (
        js_string => Text::Xslate::html_builder(
            sub {
                my $str = shift // '';
                $str =~ s/([\\'])/\\$1/g;
                return $str;
            }
        ),
    );
}

sub template_files {
    return (
        'emulatorjs.domain.conf.tt' => 'emulatorjs.domain.conf',
        'emulatorjs.index.html.tt'  => 'index.html',
    );
}

sub tests {
    return qw{emulatorjs.tt};
}

1;
