package Provisioner::Recipe::vm;

#ABSTRACT: The machine a guest runs on, rather than what runs on it.

use 5.041;

use strict;
use warnings FATAL => 'all';
use re '/aa';

use parent qw{Provisioner::Recipe};

use File::Slurper();
use Trog::HV();

=head1 NAME

Provisioner::Recipe::vm - the virtual machine itself: how big it is, what its
disks will take, and the hypervisor XML that defines it.

=head1 SYNOPSIS

    _base:
        _global:
            memory: 8192
            cpus:   4
            size:   85899345920
            disk_cache: none
            disk_total_iops_sec: 2000

=head1 DESCRIPTION

Every other recipe describes something that runs I<on> a guest.  This one
describes the guest: how much memory and how many CPUs it is promised, how large
its disk is, and every knob that decides how qemu carries its I/O.

It renders the libvirt domain XML, which is the one file here that cannot be
written until a hypervisor has answered for itself -- so unlike every other
recipe's generated files, this one is generated by C<bin/provision> rather than
by C<bin/new_config>.  See L</WHEN IT IS GENERATED>.

Its settings live in a domain's C<_global>, and are copied from there into
F<provision.conf>, which is what C<bin/provision> reads.  C<bin/recipes vm>
prints this schema, which is the description of them: F<example.test/provision.conf>
lists the keys and points here.

=head2 It directs the build rather than running in it

C<is_module> is false: there is no makefile fragment, because everything here
happens before the guest exists to run a makefile.  Every distro recipe depends
on this one -- see L<Provisioner::DistroRecipe>.

=head2 Nothing is emitted blind

libvirt has accepted most of these attributes for longer than qemu has
implemented them, so a knob this hypervisor is too old for is a domain that
either defines and will not start or starts and quietly does something else.
C<enrich> therefore asks L<Trog::HV/supports> about each one and leaves out what
this machine will not take, saying so on the way past.

The exception is the throttles.  Every other knob failing open leaves a guest
merely untuned; a throttle silently not applied leaves somebody believing in a
limit that is not there, so an unsupported one is fatal.

=head2 WHEN IT IS GENERATED

The XML names a storage volume, a backing image and a seed ISO, and it names
them by paths that do not exist until they have been made.  C<create_storage>
makes them and hands back what the template needs; C<generate_files> then
renders as any other recipe does.  Both are called from C<bin/provision>, which
is the program that has a hypervisor in hand.

The seam is deliberate.  Everything libvirt-shaped is in this recipe and its
template, so a second virtualisation platform is another recipe and another
template rather than a rewrite of C<bin/provision>.

=cut

# The limits, in the order libvirt wants them.
my @IOTUNE_KEY = qw{
  total_bytes_sec read_bytes_sec write_bytes_sec
  total_iops_sec  read_iops_sec  write_iops_sec
};

=head1 METHODS

=head2 $bool = $recipe->is_module()

False.  See L</It directs the build rather than running in it>.

=cut

sub is_module { return 0 }

=head2 %args = $recipe->args()

What a guest's machine takes.

The C<disk_*> ones deliberately declare B<no defaults>.  A default here would be
written into F<provision.conf> by C<bin/new_config>, and an absent key is how a
guest says "whatever this hypervisor decides" -- which is the whole point of
asking the hypervisor.  Their real defaults are in C<enrich>, where the answer
can depend on what libvirt and qemu will take.

=cut

sub args {
    return (
        type     => 'object',
        required => ['image'],
        ## no critic (ValuesAndExpressions::ProhibitMagicNumbers)
        properties => {
            image => {
                type        => 'string',
                description => 'Cloud image the guest disk is layered over, as a URL.  Supplied by the distro recipe; see Provisioner::DistroRecipe.',
            },
            memory => {
                type        => 'integer',
                default     => 4092,
                description => 'Memory promised to the guest, in MB.  Counted against the hypervisor as committed rather than used, since a guest promised 8G is holding 8G whether it touches it or not.',
            },
            cpus => {
                type        => 'integer',
                default     => 2,
                description => 'Virtual CPUs.  Overcommitted across the fleet, unlike memory; see hypervisors.conf.',
            },
            size => {
                type        => 'integer',
                default     => 42949672960,
                description => 'Guest disk, in bytes.  An overlay on the shared base image, so this is what it may grow to rather than what it takes now.',
            },
            cpu_mode => {
                type        => 'string',
                default     => 'host-passthrough',
                description => "libvirt <cpu mode>.  The default shows the guest the hypervisor's real CPU, including AVX and friends, which anything probing cpuid for vector extensions needs.  host-model or a named model buys migratability to a differently specced machine instead.",
            },
            disk_cache => {
                type        => 'string',
                description => "How the host caches this disk.  Defaults to none -- O_DIRECT -- so the host does not hold a second copy of every block the guest is already caching.  What that gives up is the shared base image, which writeback lets the host cache once for every guest.  A pool that will not take an O_DIRECT write is downgraded to writeback with a reason printed.",
            },
            disk_io => {
                type        => 'string',
                description => "AIO backend.  Left to qemu unless set.  io_uring is one ring shared with the kernel rather than a worker thread and a syscall per request, and needs libvirt 6.3 with qemu 5.0; native and threads are the older two.",
            },
            disk_detect_zeroes => {
                type        => 'string',
                description => "Detect all-zero writes and, with the discard path on, punch them out of the image.  Off by default: it is a check on every write for space the guest never asked to reclaim, and the guest's weekly fstrim already reclaims what it actually freed.",
            },
            disk_iothreads => {
                type        => 'integer',
                description => "Threads qemu processes this guest's disk requests on.  Defaults to 1, which is what gets submission off qemu's main loop.  More than one is worth asking for on a guest with several busy disks; one disk's queues are only spread across several threads on libvirt 10 with qemu 9.",
            },
            disk_queues => {
                type        => 'integer',
                description => 'Virtqueues on the disk.  Defaults to the vcpu count.',
            },
            disk_logical_block_size => {
                type        => 'integer',
                description => 'Logical sector size announced to the guest.  Defaults to 512.',
            },
            disk_physical_block_size => {
                type        => 'integer',
                description => 'Physical sector size announced to the guest.  Defaults to 4096, so a guest lays its filesystem out for 4K rather than doing read-modify-write against 4K hardware for the life of the disk.  This has to be right before the guest makes its filesystem; changing it afterwards realigns nothing.',
            },
            map {
                (
                    "disk_$_" => {
                        type        => 'integer',
                        description =>
                          "libvirt iotune $_.  Unset by default: hypervisors.conf reserves memory, CPUs and disk space and reserves nothing of the I/O every guest on the machine shares a queue for, and this is the knob that answers that.  Applied per disk rather than per domain, so a guest with three disks can do three times what a number here says.  A total may not be given alongside the halves it is the total of.",
                    }
                )
            } @IOTUNE_KEY,
        },
    );
}

=head2 %files = $recipe->template_files()

The domain XML, and the hypervisor's half of the guest's logging.

=cut

sub template_files {
    return (
        'vm.domain.xml.tt'             => 'domain.xml',
        'vm.devices.map.tt'            => 'devices.map',
        'vm.rsyslog-collector.conf.tt' => 'rsyslog-collector.conf',
        'vm.logrotate.conf'            => 'logrotate.conf',
    );
}

=head2 %facts = $recipe->create_storage(%opts)

Make what the domain XML is going to point at, and hand back the paths.

The storage pool if the hypervisor has none, the base image if it has not
downloaded one, this guest's disk as an overlay on it, and the cloud-init seed
ISO out of the three NoCloud files.  All four are on the hypervisor, and none of
their paths can be written into the XML before they exist -- which is why this
is separate from rendering rather than something C<enrich> could do.

C<seed> is the three NoCloud files as a hash; cloud-init will not look at a seed
missing any of them, so an absent one is an error here rather than a guest that
boots without a user on it.

=cut

sub create_storage {
    my ( $self, %opts ) = @_;

    my $hv     = $self->hv;
    my $domain = $opts{domain};

    foreach my $file (qw{user-data meta-data network-config}) {
        die "No $file to build the cloud-init seed for $domain from\n"
          unless defined $opts{seed}{$file} && length $opts{seed}{$file};
    }

    my $volume = "$domain-qcow2";
    $hv->pool();
    my $base = $hv->base_image( $opts{image} );
    $hv->create_disk( $volume, backing => $base, capacity => $opts{size} );

    my %qcow2 = $hv->qcow2_tuning( $opts{size} );

    return (
        pool_name      => 'tf_disks',
        disk_volume    => $volume,
        cloudinit      => $hv->cloudinit_iso( $domain, %{ $opts{seed} } ),
        bridge_device  => $hv->bridge_device,
        nat_mac        => $hv->guest_mac( $domain, 0 ),
        bridge_mac     => $hv->guest_mac( $domain, 1 ),
        metadata_cache => $qcow2{metadata_cache},
    );
}

=head2 $hv = $recipe->hv()

The hypervisor this guest is being built for, out of the singleton the run
already established -- unless one was handed to the constructor, which is what a
test does.

Reached here rather than from L<Provisioner::Recipe>, so that loading an
ordinary recipe does not load L<Sys::Virt> along with it.

=cut

sub hv { my ($self) = @_; return $self->{hv} //= Trog::HV->new() }

=head2 %opts = $recipe->enrich(%opts)

Work out what this hypervisor will actually accept, and what each of the guest's
disks therefore looks like.

Everything here is a decision rather than a string: which cache mode, how many
iothreads, which disk gets which one, what came out of F<mounts.txt>.  The
template does the writing.

=cut

sub enrich {
    my ( $self, %opts ) = @_;

    my $hv        = $self->hv;
    my $iothreads = $self->_iothreads( \%opts );

    my %tuning = (
        cache            => $self->_cache( \%opts ),
        io               => $self->_io( \%opts ),
        discard          => $hv->supports('discard') ? 1 : 0,
        detect_zeroes    => $self->_detect_zeroes( \%opts ),
        discard_no_unref => $hv->supports('discard_no_unref') ? 1 : 0,
        iothreads        => $iothreads,
        mapping          => ( $iothreads > 1 && $hv->supports('iothread_mapping') ) ? 1 : 0,
        queues           => $self->_queues( \%opts ),
        blockio          => $self->_blockio( \%opts ),
        iotune           => $self->_iotune( \%opts ),

        # Not worked out here: it is a function of how large the image is, so
        # create_storage asks the hypervisor and hands it over.
        metadata_cache => $opts{metadata_cache},
    );

    $opts{tuning} = \%tuning;
    $opts{tpm}    = $self->_tpm;

    my ( $disks, $filesystems, $devices ) = $self->_devices( \%opts, \%tuning );
    $opts{disks}       = $disks;
    $opts{filesystems} = $filesystems;
    $opts{devices_map} = $devices;

    return %opts;
}

# A guest gets an emulated TPM if, and only if, the hypervisor has a real one.
#
# swtpm keeps a guest's TPM state in a file on the hypervisor, so a key sealed to
# it is sealed to a file sitting beside the guest's own disk image: whoever takes
# the disk takes the TPM with it.  That is worth having when the hypervisor's own
# disk is protected by hardware, and worth less than nothing when it is not,
# because something on the guest will use it and believe it.
sub _tpm {
    my ($self) = @_;
    return 1 if $self->hv->has_tpm;

    print "No hardware TPM on the hypervisor, so this guest gets none either\n";
    return 0;
}

# An absent key and a key with nothing after the '=' are both "no answer".
# Config::Simple tells them apart and nothing here wants to.
sub _asked {
    my ( $opts, $key ) = @_;
    return undef unless defined $opts->{$key} && length $opts->{$key};
    return $opts->{$key};
}

# cache='none' is the only knob here that no version can answer for.
#
# Unset, qemu caches every guest block in the host's page cache as well as the
# guest's own -- so a hypervisor holds two copies of everything, in memory that
# Trog::Hypervisors is not counting when it decides what else fits.  O_DIRECT
# gives that back.  What it costs is the shared base image: every guest is an
# overlay on one file, and writeback means the host caches that file once for
# all of them.  That is a real trade rather than a free win, which is why it is
# a key rather than a constant.
#
# What decides it is whether the pool's filesystem will take an O_DIRECT write,
# since one that will not fails qemu's open and the domain defines cleanly and
# then refuses to start.  That is asked of the filesystem: see
# Trog::HV::pool_takes_direct_io for why naming filesystems does not work.
sub _cache {
    my ( $self, $opts ) = @_;
    my $hv = $self->hv;

    my $asked = _asked( $opts, 'disk_cache' );
    return $asked if $asked;
    return 'none' if $hv->pool_takes_direct_io;

    print "The storage pool, on " . $hv->pool_fstype . ", would not take an O_DIRECT write, so this\n" . "guest gets cache='writeback' rather than a domain that defines and then won't start.\n" . $self->_direct_io_advice . "Set disk_cache in provision.conf to say otherwise.\n";
    return 'writeback';
}

# Which of the two ZFS answers this is, when it is ZFS: a release with no Direct
# I/O at all, or one that has it and a pool or a dataset configured not to use
# it.  An operator can act on either, and can act on neither if all they are
# told is that the filesystem said no.
sub _direct_io_advice {
    my ($self) = @_;
    my $hv = $self->hv;
    return '' unless $hv->pool_fstype eq 'zfs';

    my $version = $hv->zfs_version;
    return "The pool is on ZFS and the hypervisor would not say which version; ask it with\n" . "`cat /sys/module/zfs/version`.\n"
      unless defined $version;

    return "OpenZFS is $version here and Direct I/O arrived in 2.3, so this wants an upgrade.\n"
      if _zfs_predates_direct_io($version);

    return "OpenZFS $version has Direct I/O, so it is the pool or the dataset refusing it:\n" . "`zpool get all` for the feature flags, `zfs get direct` for the property.\n";
}

# 2.10 is a later release than 2.3, which a string comparison gets backwards.
sub _zfs_predates_direct_io {
    my ($version) = @_;
    my ( $major, $minor ) = $version =~ m/^(\d+)[.](\d+)/ or return 0;
    return ( ( $major * 1_000 ) + $minor ) < 2_003 ? 1 : 0;
}

# Left to qemu unless asked for: the AIO backend is the one thing on this list
# the domain template used to set and no longer does, and turning it back on
# behind somebody's back is not this function's business.  disk_io=io_uring
# reinstates it, on a hypervisor whose qemu has it.
sub _io {
    my ( $self, $opts ) = @_;
    my $hv = $self->hv;

    my $asked = _asked( $opts, 'disk_io' ) or return undef;
    return $asked unless $asked eq 'io_uring';
    return 'io_uring' if $hv->supports('io_uring');

    print "disk_io=io_uring needs libvirt 6.3 and qemu 5.0; " . $hv->describe . " has older,\n" . "so the disk is left on qemu's own choice of AIO backend.\n";
    return undef;
}

# Off unless asked for, which is a deliberate departure from "turn the discard
# path on".  detect_zeroes='unmap' makes qemu inspect every write for a buffer
# of zeros, on the write path, for the sake of reclaiming space the guest never
# asked to reclaim -- and the guest's weekly fstrim, which discard='unmap' now
# passes through, reclaims what it actually freed without spending anything per
# write.  Worth having on a guest that genuinely writes zeros in bulk; not worth
# it as a default for every guest.
sub _detect_zeroes {
    my ( $self, $opts ) = @_;
    my $hv = $self->hv;

    my $asked = _asked( $opts, 'disk_detect_zeroes' ) or return undef;
    return $asked if $hv->supports('detect_zeroes');

    print "disk_detect_zeroes needs libvirt 2.0; " . $hv->describe . " has older, so it is left off.\n";
    return undef;
}

# One by default: without it, virtio-blk submission runs on qemu's main loop,
# serialised against everything else that loop does.  More than one is only
# worth asking for on a guest with several busy disks, or on a hypervisor new
# enough to spread one disk's queues across them -- see _disk_attrs.
sub _iothreads {
    my ( $self, $opts ) = @_;
    my $hv = $self->hv;

    my $asked = _asked( $opts, 'disk_iothreads' ) // 1;
    return 0      if $asked <= 0;
    return $asked if $hv->supports('iothread');

    print "disk_iothreads needs libvirt 1.2.8 and qemu 2.1; " . $hv->describe . " has older,\n" . "so this guest's disks stay on qemu's main loop.\n";
    return 0;
}

# One virtqueue per vcpu unless told otherwise.  Recent qemu sizes virtio-blk
# this way itself, so on most of the fleet this says out loud what was already
# happening -- but it has to be said out loud to be mapped across iothreads.
sub _queues {
    my ( $self, $opts ) = @_;
    return undef unless $self->hv->supports('queues');

    my $asked = _asked( $opts, 'disk_queues' ) // $opts->{cpus};
    return $asked > 0 ? $asked : undef;
}

# What the guest is told its sectors are.  virtio-blk says 512/512 by default,
# so a guest lays its filesystem out for 512 byte sectors and then does
# read-modify-write against 4K hardware underneath for the life of the disk.
#
# This has to be right before the guest's filesystem is made; setting it on an
# existing guest realigns nothing.  4096 is safe to announce even on a 512n
# device -- the guest merely aligns to a boundary that device does not care
# about -- which is why it is the default rather than something probed.
sub _blockio {
    my ( $self, $opts ) = @_;
    return undef unless $self->hv->supports('blockio');

    ## no critic (ValuesAndExpressions::ProhibitMagicNumbers)
    return {
        logical  => _asked( $opts, 'disk_logical_block_size' )  // 512,
        physical => _asked( $opts, 'disk_physical_block_size' ) // 4096,
    };
}

# hypervisors.conf reserves memory, CPUs and disk space, and reserves nothing at
# all of the one resource every guest on a machine is sharing a queue for.  One
# guest running a backup can flatten every other guest in the pool and no
# capacity check will have predicted it.  This is the knob that answers that;
# it is off unless a guest is given limits, because a throttle is a cost and
# only the person who knows the workload can say what it should be.
#
# Unsupported is fatal rather than skipped: every other knob here failing open
# leaves a guest merely untuned, but a throttle silently not applied leaves
# somebody believing in a limit that is not there.
#
# A list rather than a hash, because libvirt wants these in its own order and
# the template should not have to know what that order is.
sub _iotune {
    my ( $self, $opts ) = @_;
    my $hv = $self->hv;

    my %limit = map { $_ => _asked( $opts, "disk_$_" ) } @IOTUNE_KEY;
    delete @limit{ grep { !defined $limit{$_} } keys %limit };
    return undef unless %limit;

    die "disk_*_bytes_sec/disk_*_iops_sec need libvirt 0.9.8, and " . $hv->describe . " is older.\n" . "Remove them from provision.conf, or build this guest somewhere that can honour them.\n"
      unless $hv->supports('iotune');

    # libvirt's own rule: a total is a total, and may not be given beside the
    # halves it is the total of.
    foreach my $unit (qw{bytes_sec iops_sec}) {
        next unless $limit{"total_$unit"};
        die "disk_total_$unit cannot be set alongside disk_read_$unit or disk_write_$unit:\n" . "libvirt takes a total or the two halves, never both.\n"
          if $limit{"read_$unit"} || $limit{"write_$unit"};
    }

    return [ map { { name => $_, value => $limit{$_} } } grep { defined $limit{$_} } @IOTUNE_KEY ];
}

# Everything the domain has hanging off it: its own disk first, then whatever
# mounts.txt asked for, and the map the guest is handed so it can find them.
#
# Each line of mounts.txt is pool=name.  A `raw` pool is a host block device,
# `dir` is a directory shared in over virtiofs, `file` is an image file, and
# anything else is taken as the name of another libvirt pool.  `fuse` is
# skipped: the guest mounts those itself.
sub _devices {
    my ( $self, $opts, $tuning ) = @_;

    my @disks = ( $self->_disk( $tuning, format => 'qcow2', dev => 'vda', boot => 1, index => 0, primary => 1 ) );
    my ( @filesystems, $map );
    $map = '';

    my $spec_file = "$self->{output_dir}/mounts.txt";
    ## no critic (ValuesAndExpressions::ProhibitFiletest_r)
    if ( -r $spec_file ) {
        my @devnames = ( 'vdb' .. 'vdz' );
        my $order    = 2;
        my $index    = 0;

        foreach my $diskspec ( grep { $_ } split( "\n", File::Slurper::read_text($spec_file) ) ) {
            my ( $pool, $disk ) = split( '=', $diskspec );
            next if $pool eq 'fuse';

            $order++;
            my $dev = shift @devnames or die "Ran out of vdnames!\n";

            # The guest gets a map of what it asked for to where it landed.
            $map .= $pool eq 'dir' ? "$disk=$dev\n" : "$disk=/dev/$dev\n";

            if ( $pool eq 'dir' ) {
                push( @filesystems, { source => $disk, target => $dev } );
                next;
            }

            $index++;

            if ( $pool eq 'raw' ) {
                push( @disks, $self->_disk( $tuning, format => 'raw', dev => $dev, boot => $order, index => $index, type => 'block', source => $disk ) );
                next;
            }

            # A file, or a volume in some other pool -- either way it resolves
            # to a path, and libvirt wants the path.
            my $path = $pool eq 'file' ? $disk : ( $self->hv->volume_path( $disk, $pool ) // $disk );
            push( @disks, $self->_disk( $tuning, format => 'qcow2', dev => $dev, boot => $order, index => $index, type => 'file', source => $path ) );
        }
    }

    return ( \@disks, \@filesystems, $map );
}

# One disk, with every attribute already decided.  The template writes what is
# here and works nothing out, which is the difference between a template and the
# string concatenation this replaced.
sub _disk {
    my ( $self, $tuning, %disk ) = @_;

    $disk{type} //= 'volume';

    # A qcow2 knob, and the extra disks are not all qcow2: on a raw block device
    # there is no cluster to keep the reference to.  What it does buy, on the
    # ones that are, is a guest discard that punches the hole in the host's
    # filesystem without unrefing the cluster in the image -- so the space comes
    # back without the qcow2 fragmenting itself rewriting what it just freed.
    $disk{discard_no_unref} = ( $tuning->{discard_no_unref} && $disk{format} eq 'qcow2' ) ? 1 : 0;

    # iothread and iothreads are mutually exclusive, and the mapping only goes
    # on the disk it was worked out for.  Everything else gets one iothread out
    # of the pool, round robin, so a guest with several disks spreads them --
    # and with the default pool of one they share it and are still off the main
    # loop, which is the part that mattered.
    my $mapped = $disk{primary} && $tuning->{mapping};
    $disk{iothread} = ( $disk{index} % $tuning->{iothreads} ) + 1
      if $tuning->{iothreads} && !$mapped;

    # Listed without queue children on purpose: given the iothreads and the
    # queue count, libvirt and qemu distribute the virtqueues between them, and
    # a mapping written out by hand here would only be the same answer with more
    # ways to get it wrong.
    $disk{iothread_ids} = $mapped ? [ 1 .. $tuning->{iothreads} ] : [];

    # The metadata cache is a function of how large the image is, so only the
    # disk whose size we know gets one.
    $disk{metadata_cache} = $tuning->{metadata_cache} if $disk{primary};

    return \%disk;
}

1;
