#!/bin/bash

PATH="/usr/libexec/dovecot:$PATH"

# $1 is mail recipient from dovecot

[[ -z $1 ]] && exit 1;

dovecot-lda -d $1 -o "plugin/quota=maildir:User quota:noenforcing" <<MAIL
From: postmaster@$(hostname -f)
To: $1
Date: $(date --rfc-2822)
Subject: This mailbox is nearly over its quota
Mime-Version: 1.0
Content-Type: text/plain; charset=iso-8859-1
Content-Transfer-Encoding: 7bit

Greetings!

Delete any mail you don't need after backing it up
and/or reply to this mail in supplication of more bytes.

Alternatively, do nothing and cease to recieve mail.
We get paid the same either way.

Thanks,

- The Management

MAIL
