#!/bin/bash

# Make a DKIM record for a domain and install it into the pdns server for that
# domain.

# Do nothing if the pdns database for the domain is not there.
[[ ! -f /var/spool/powerdns/$1/zones.db ]] && exit 0;

# Do nothing if the DKIM key is not there.
[[ ! -f /mail/keys/$1/default.private ]] && exit 0;

DKIM_KEY=$(openssl rsa -in /etc/opendkim/keys/$1/default.private -pubout 2>/dev/null | sed "1,1d;$ d;" | sed -z "s/\n//g")

if [ -z "$DKIM_KEY" ]
then
	echo "Can't extract public key from private dkim key for $1."
	exit 1;
fi

DKIM_RECORD="v=DKIM1; h=sha256; k=rsa; t=y; p=$DKIM_KEY"

echo "Installing DKIM Key:"
echo "$DKIM_RECORD"

SQL="insert or replace into records (domain_id, name, type,content,ttl,prio,disabled) select id , 'default._domainkey.$1', 'TXT', '$DKIM_RECORD', 300, 0, 0 from domains where name='$1'"
echo "$SQL" | sqlite3 /var/spool/powerdns/$1/zones.db
SQL="insert or replace into records (domain_id, name, type,content,ttl,prio,disabled) select id , 'mail._domainkey.$1', 'TXT', '$DKIM_RECORD', 300, 0, 0 from domains where name='$1'"
echo "$SQL" | sqlite3 /var/spool/powerdns/$1/zones.db

systemctl restart pdns

# TODO: Move the registrar code below into a separate recipe that does all the
# DNS work with the registrar.  Until then, it does not run.
exit 0;
# If the domain has a lexicon shortcut, update the records at the registrar.
[ -x "/opt/lexicon/$1" ] || exit 0;

EXISTING_RECORDS=$(/opt/lexicon/$1 list TXT)
if echo "$EXISTING_RECORDS" | grep -q "mail._domainkey.$1."
then
	/opt/lexicon/$1 update TXT --name="mail._domainkey.$1." --content="$DKIM_RECORD"
else
	/opt/lexicon/$1 create TXT --name="mail._domainkey.$1." --content="$DKIM_RECORD"
fi

if echo "$EXISTING_RECORDS" | grep -q "default._domainkey.$1."
then
	/opt/lexicon/$1 update TXT --name="default._domainkey.$1." --content="$DKIM_RECORD"
else
	/opt/lexicon/$1 create TXT --name="default._domainkey.$1." --content="$DKIM_RECORD"
fi
