#!/bin/bash

# Reboot if the system says that it needs a reboot.
# If you give a file as the argument, reboot only when that file also exists.
[ -f $1 ] || [ -z $1 ] && [ -f /var/run/reboot-required ] && reboot now
